spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookpie2022@gmail.com
    password: ^4jy0#aaw7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: 127.0.0.1
    port: 6379